### ISSUE TITLE
pyatac pwm: OverflowError: can't convert negative value to unsigned int

### ISSUE THREAD

**Issue by jebard** [GreenleafLab/NucleoATAC#10]
Hello! I've been playing around with the pyatac pwm command, and have been getting an error when running with default settings.

pyatac pwm --fasta genome.fa --bam BWA.10.bam --cores 10
Command run:  /data/apps/NucleoATAC/bin/pyatac pwm --fasta genome.fa --bam BWA.10.bam --cores 10
pyatac version 0.2.1
start run at: 2015-09-02 15:21
---------Making PWM from bam---------------------------------------
Caught exception when processing:
chr1    8010    9010    1       region  *

Traceback (most recent call last):
  File "/user/jbard/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/get_pwm.py", line 30, in _pwmHelper
    ins.calculateInsertions( params.bam, lower = params.lower, upper = params.upper, atac = params.atac)
  File "/user/jbard/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/tracks.py", line 168, in calculateInsertions
    self.vals = getInsertions(bamfile, self.chrom, self.start, self.end, lower, upper, atac)
  File "pyatac/fragments.pyx", line 56, in pyatac.fragments.getInsertions (/user/jbard/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:2896)
    ilen = abs(read.template_length) - 8
OverflowError: can't convert negative value to unsigned int
()
Traceback (most recent call last):
  File "/data/apps/NucleoATAC/bin/pyatac", line 359, in <module>
    main()
  File "/data/apps/NucleoATAC/bin/pyatac", line 67, in main
    get_pwm(args)
  File "/user/jbard/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/get_pwm.py", line 72, in get_pwm
    tmp = pool.map(_pwmHelper, zip(sets,itertools.repeat(params)))
  File "/util/academic/python/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/util/academic/python/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OverflowError: can't convert negative value to unsigned int

**Comment by AliciaSchep** [comment]
Do you have any fragments that would have length less than 8 bp in your bam file?

**Comment by jebard** [comment]
There were fragments shorter than 8bp. When doing alignments using bwa-mem I believe the soft clipping generated these short fragments. I've rerun the analysis using a bowtie2 generated BAM and have no issue. Thanks for the suggestion!
