### ISSUE TITLE
chromsome discrepancy

### ISSUE THREAD

**Issue by davek44** [GreenleafLab/NucleoATAC#11]
You might consider making the program robust to discrepancies between the chromosomes in the genome FASTA file and the chromosomes to which the reads were aligned. If one downloads the BAMs from a public repository like GEO, one won't necessarily have aligned to exactly the same chromosome. And it's frustrating for the program to run for a week before letting me know that was a problem! Here's the error in case you want to look into it. I'd be completely ok with the program ignoring chr9_gl000200_random if it's a problem.

_---------Step5: Calling NFR positions-------------------------------------------
Traceback (most recent call last):
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_nfr.py", line 26, in _nfrHelper
    nfr.process(params)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/NFRCalling.py", line 105, in process
    self.findNFRs()
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/NFRCalling.py", line 89, in findNFRs
    for row in tbx.fetch(self.chrom, self.start, self.end, parser = pysam.asTuple()):
  File "pysam/ctabix.pyx", line 408, in pysam.ctabix.TabixFile.fetch (pysam/ctabix.c:4826)
ValueError: could not create iterator for region 'chr9_gl000200_random:87781-88154'
Traceback (most recent call last):
  File "/n/home03/dkelley/.local/bin/nucleoatac", line 5, in <module>
    pkg_resources.run_script('NucleoATAC==0.2.1', 'nucleoatac')
  File "/n/home03/dkelley/lib/python2.7/site-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/n/home03/dkelley/lib/python2.7/site-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 291, in <module>
    main()
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 83, in main
    run_nfr(nfr_args)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_nfr.py", line 98, in run_nfr
    tmp = pool1.map(_nfrHelper, zip(j,itertools.repeat(params)))
  File "/n/home03/dkelley/envs/DK/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/n/home03/dkelley/envs/DK/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: could not create iterator for region 'chr9_gl000200_random:87781-88154'
Traceback (most recent call last):
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_nfr.py", line 26, in _nfrHelper
    nfr.process(params)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/NFRCalling.py", line 105, in process
    self.findNFRs()
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/NFRCalling.py", line 89, in findNFRs
    for row in tbx.fetch(self.chrom, self.start, self.end, parser = pysam.asTuple()):
  File "pysam/ctabix.pyx", line 408, in pysam.ctabix.TabixFile.fetch (pysam/ctabix.c:4826)_

**Comment by AliciaSchep** [comment]
Ok I'll add a check at the beginning to see if the chromosomes between peaks and fasta are compatible, with the program ignoring chromosomes that are missing from fasta but with a warning to alert that chromosomes are being ignored
