### ISSUE TITLE
Problem running NucleoAtac

### ISSUE THREAD

**Issue by kesteph** [GreenleafLab/NucleoATAC#12]
Hello
I'm trying to run NucleoATAC, but I receive the following error:

[compute-078]$ nucleoatac run --bed KSN_C_peaks.narrowPeak.sorted.slopped.bed --bam KSN_C.bam --fasta rn5.fa --out KSN_C.NucleoATAC
Command run:  /home/jhmi/kstephen/.local/bin/nucleoatac run --bed KSN_C_peaks.narrowPeak.sorted.slopped.bed --bam KSN_C.bam --fasta mm9.fa --out KSN_C.NucleoATAC
nucleoatac version 0.2.1
start run at: 2015-09-17 20:46
Traceback (most recent call last):
  File "/home/jhmi/kstephen/.local/bin/nucleoatac", line 4, in <module>
    **import**('pkg_resources').run_script('NucleoATAC==0.2.1', 'nucleoatac')
  File "/jhpce/shared/community/compiler/gcc/4.4.7/python/2.7.6/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/jhpce/shared/community/compiler/gcc/4.4.7/python/2.7.6/lib/python2.7/site-packages/pkg_resources.py", line 1423, in run_script
    exec(code, namespace, namespace)
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 291, in <module>
    main()
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 69, in main
    from nucleoatac.run_occ import run_occ
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_occ.py", line 19, in <module>
    from nucleoatac.Occupancy import FragmentMixDistribution, OccupancyParameters, OccChunk
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/Occupancy.py", line 12, in <module>
    from pyatac.fragmentsizes import FragmentSizes
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/fragmentsizes.py", line 10, in <module>
    from pyatac.fragments import getAllFragmentSizes, getFragmentSizesFromChunkList
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 435, in load_module
    language_level=self.language_level)
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 227, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 209, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 174, in build_module
    extension_mod,setup_args = get_distutils_extension(name, pyxfilename, language_level)
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 94, in get_distutils_extension
    extension_mod,setup_args = handle_special_build(modname, pyxfilename)
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/pyximport/pyximport.py", line 118, in handle_special_build
    ext = make_ext(modname, pyxfilename)
  File "/home/jhmi/kstephen/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/fragments.pyxbld", line 7, in make_ext
    extra_link_args=pysam.get_libraries(),
ImportError: Building module pyatac.fragments failed: ["AttributeError: 'module' object has no attribute 'get_libraries'\n"]

I'm running python 2.7.6 with spicy version 0.15.1, numpy version 1.9.2, & python  version 0.23.2 on red hat 4.4.7-4

thank you
Kim

**Comment by AliciaSchep** [comment]
What is version of pysam?  (Error appears to be in pysam.get_libraries() that is called while building one of the files)

**Comment by kesteph** [comment]
Pysam version 0.8.3

**Comment by antgomo** [comment]
Having same problem with NucleoATAC-0.3.1

Pysam version pysam-0.8.4

**Comment by kesteph** [comment]
I reinstalled pysam and this seemed to fix my issue
