### ISSUE TITLE
nucleoATAC Invalid Region error

### ISSUE THREAD

**Issue by OscarBrock** [GreenleafLab/NucleoATAC#20]
Hello, I'm getting the following error when running nucleoATAC on sorted BAM files and the output of MACS2 as inputs. I'm using python 2.7, numpy 1.9.3, scipy 0.16.0, cython 0.23.3, pysam 0.8.3. 

Any help would be appreciated.  

-R
# 

Relevant error text:

(ATACseq)[bainerr@rescomp5008 ATACpilot]$ nucleoatac run --bed /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/macs2_results/filtered.lungline_10_peaks.broadPeak --bam /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/filtered.lungline_10.bam --fasta /gne/research/apps/ngs_pipeline/3.14.2/x86_64-linux-2.6-sles11/genome_files/GATK/NCBIM37.fa --out lungline_nATAC_10
Command run:  /gne/home/bainerr/bin/nucleoatac run --bed /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/macs2_results/filtered.lungline_10_peaks.broadPeak --bam /gne/home/bainerr/Workspace/ATACseq/Jackson/ATACpilot/filtered.lungline_10.bam --fasta /gne/research/apps/ngs_pipeline/3.14.2/x86_64-linux-2.6-sles11/genome_files/GATK/NCBIM37.fa --out lungline_nATAC_10
nucleoatac version 0.2.1
start run at: 2015-10-09 13:53
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Caught exception when processing:
10      129994094       129994223       None    None    +

Traceback (most recent call last):
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_occ.py", line 30, in _occHelper
    occ.process(params)
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/Occupancy.py", line 226, in process
    self.makeBiasMat()
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/Occupancy.py", line 195, in makeBiasMat
    bias_track.computeBias(self.params.fasta, self.params.chrs, self.params.pwm)
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/bias.py", line 88, in computeBias
    sequence = seq.get_sequence(self, fasta)
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/seq.py", line 18, in get_sequence
    sequence = handle.fetch(chunk.chrom, chunk.start, chunk.end)
  File "pysam/cfaidx.pyx", line 182, in pysam.cfaidx.FastaFile.fetch (pysam/cfaidx.c:3370)
ValueError: invalid region: start (129993838) > end (129993255)
()
Traceback (most recent call last):
  File "/gne/home/bainerr/bin/nucleoatac", line 291, in <module>
    main()
  File "/gne/home/bainerr/bin/nucleoatac", line 75, in main
    run_occ(occ_args)
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_occ.py", line 116, in run_occ
    tmp = pool1.map(_occHelper, zip(j,itertools.repeat(params)))
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: invalid region: start (129993838) > end (129993255)

**Comment by AliciaSchep** [comment]
I suspect given the coordinates that something strange is happening with that peak because it is at the end of the chromosome; I think such peaks ought to be handled correctly (I have done some tests to see that both peaks at very beginning and end are handled correctly) but that they might not be if the chromosome length information differs between the fasta and the bam file.  Can you confirm that the fasta file provided matches exactly the genome file used for alignment? i.e. if you do  in python interpreter:

``` python
from pyatac.utils read_chrom_sizes_from_bam, read_chrom_sizes_from_fasta
read_chrom_sizes_from_fasta('name_of_fasta_file')['10']
read_chrom_sizes_from_bam('name_of_bam_file')['10']
```

are the results the same?

**Comment by OscarBrock** [comment]
Hi Alicia,

Thanks for your prompt attention. I'm pretty sure that the bams were
aligned using the correct assembly, but I'm afraid that I don't program in
python and need a bit more direction. I am currently getting a syntax error
when run that code within the interpreter (within the environment that I
use to run nucleoATAC):

> > > from pyatac.utils read_chrom_sizes_from_bam, read_chrom_sizes_from_fasta
> > >   File "<stdin>", line 1
> > >     from pyatac.utils read_chrom_sizes_from_bam,
> > > read_chrom_sizes_from_fasta
> > >                                               ^
> > > SyntaxError: invalid syntax

I'm sure it's something obvious?

-R

**Comment by AliciaSchep** [comment]
Sorry about that, I left out a crucial word-- should be:

``` python
from pyatac.utils import read_chrom_sizes_from_bam, read_chrom_sizes_from_fasta
```

**Comment by OscarBrock** [comment]
Ha! You were right- they apparently updated the default genome assembly
here a couple of days ago. Everything seems to be running here now, I'll
start another thread if I run into additional problems.

Thanks for your help with this.

**Comment by OscarBrock** [comment]
Hi Alicia, 

I'm afraid that I am running into a similar issue, this time during the nfr calling step. I'm sure that my alignment and fasta match now, and notably the code appears to progress despite throwing the errors. I thought I'd pass them along to see if you have any insight about what could be going on. 

# 

---------Step5: Calling NFR positions-------------------------------------------
Traceback (most recent call last):
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/run_nfr.py", line 26, in _nfrHelper
    nfr.process(params)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/NFRCalling.py", line 105, in process
    self.getBias()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/NFRCalling.py", line 83, in getBias
    self.bias.computeBias(self.params.fasta, self.params.chrs, self.params.pwm)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyatac/bias.py", line 88, in computeBias
    sequence = seq.get_sequence(self, fasta)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyatac/seq.py", line 18, in get_sequence
    sequence = handle.fetch(chunk.chrom, chunk.start, chunk.end)
  File "pysam/cfaidx.pyx", line 182, in pysam.cfaidx.FastaFile.fetch (pysam/cfaidx.c:3370)
ValueError: invalid region: start (195585088) > end (195471971)
Traceback (most recent call last):
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 291, in <module>
    main()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 83, in main
    run_nfr(nfr_args)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/run_nfr.py", line 104, in run_nfr
    tmp = pool1.map(_nfrHelper, zip(j,itertools.repeat(params)))
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: invalid region: start (195585088) > end (195471971)
