### ISSUE TITLE
Overflow error

### ISSUE THREAD

**Issue by OscarBrock** [GreenleafLab/NucleoATAC#21]
Hi all, 

I'm getting an overflow error during the NFR call step. Any ideas? 

---------Step5: Calling NFR positions-------------------------------------------
Traceback (most recent call last):
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_nfr.py", line 26, in _nfrHelper
    nfr.process(params)
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/NFRCalling.py", line 103, in process
    self.getIns()
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/NFRCalling.py", line 74, in getIns
    self.ins.calculateInsertions(self.params.bam)
  File "/gne/home/bainerr/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/tracks.py", line 168, in calculateInsertions
    self.vals = getInsertions(bamfile, self.chrom, self.start, self.end, lower, upper, atac)
  File "pyatac/fragments.pyx", line 56, in pyatac.fragments.getInsertions (/gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:2973)
    ilen = abs(read.template_length) - 8
OverflowError: can't convert negative value to unsigned int

**Comment by AliciaSchep** [comment]
Yes, this is an issue with having fragments less than 8 bp (something I hadn't expected in ATAC samples, but can result from aligners clipping fragments).  Such short fragments are definitely artifacts given how Tn5 works.  I have made a fix to change this error from coming up; it should be implemented in version 0.2.2 + (such tiny fragments are just ignored), so hopefully if you update version this error won't occur anymore

**Comment by AliciaSchep** [comment]
Alternatively, filtering out such tiny fragments will also prevent this error

**Comment by OscarBrock** [comment]
Ah, great. Thank you.

-R
