### ISSUE TITLE
Problems running example

### ISSUE THREAD

**Issue by antgomo** [GreenleafLab/NucleoATAC#27]
Once installed NucleoATAC I have this error with the example files

Command run:  /nfs/software/tgraf/python/envs/cpython279/bin/nucleoatac run --bed example.bed --bam example.bam --fasta sacCer3.fa --out test_example
nucleoatac version 0.3.1
start run at: 2015-11-04 18:25
Traceback (most recent call last):
  File "/nfs/software/tgraf/python/envs/cpython279/bin/nucleoatac", line 4, in <module>
    **import**('pkg_resources').run_script('NucleoATAC==0.3.1', 'nucleoatac')
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/pkg_resources/**init**.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/NucleoATAC-0.3.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 291, in <module>
    main()
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/NucleoATAC-0.3.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 69, in main
    from nucleoatac.run_occ import run_occ
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/NucleoATAC-0.3.1-py2.7.egg/nucleoatac/run_occ.py", line 9, in <module>
    import matplotlib as mpl
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/matplotlib/**init**.py", line 1131, in <module>
    rcParams = rc_params()
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/matplotlib/**init**.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/matplotlib/**init**.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/software/tgraf/python/pythons/CPython-2.7.9/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/site-packages/matplotlib/**init**.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/nfs/software/tgraf/python/envs/cpython279/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Dependencies installed

Cython (0.23.4)
matplotlib (1.5.0)
NucleoATAC (0.3.1)
numpy (1.10.1)
pysam (0.8.3)
scipy (0.16.1)

**Comment by wgb** [comment]
It's likely that the UTF-8 locale is not installed or enabled on the system. Follow the steps [here](https://wiki.archlinux.org/index.php/Locale#Generating_locales) to enable the UTF-8 locale on the system and it will likely fix the issue.
