### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by lopatica** [GreenleafLab/NucleoATAC#3]
I am having trouble deciphering why the command crashes. Any help would be very appreciated. 

Command run:  ./nucleoatac run --bed /wsu/home/ba/ba02/ba0287/nucleosomedata/wt/nucleoatac/macs2/tg_peaks_slop.bed --bam /wsu/home/ba/ba02/ba0287/nucleosomedata/wt/tg_mononucleosomes/alignments/tg_mono.q10.s.bam --fasta /wsu/home/ba/ba02/ba0287/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/Mm10.fa --out tg
nucleoatac version 0.1.3
start run at: 2015-04-14 20:15
/wsu/apps/gnu-4.7.2/python/Anaconda/Anaconda-2.1.0/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/pkg_resources.py:1032: UserWarning: /wsu/home/ba/ba02/ba0287/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Traceback (most recent call last):
  File "./nucleoatac", line 4, in <module>
    **import**('pkg_resources').run_script('NucleoATAC==0.1.3', 'nucleoatac')
  File "/wsu/apps/gnu-4.7.2/python/Anaconda/Anaconda-2.1.0/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/pkg_resources.py", line 517, in run_script
  File "/wsu/apps/gnu-4.7.2/python/Anaconda/Anaconda-2.1.0/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/pkg_resources.py", line 1423, in run_script
  File "/wsu/home/ba/ba02/ba0287/lib/python/NucleoATAC-0.1.3-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 217, in <module>
    main()
  File "/wsu/home/ba/ba02/ba0287/lib/python/NucleoATAC-0.1.3-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 58, in main
    run_occ(occ_args)
  File "/wsu/home/ba/ba02/ba0287/lib/python/NucleoATAC-0.1.3-py2.7.egg/nucleoatac/run_occ.py", line 82, in run_occ
    chunks.merge()
  File "/wsu/home/ba/ba02/ba0287/lib/python/NucleoATAC-0.1.3-py2.7.egg/pyatac/chunk.py", line 104, in merge
    previous = self[0]
IndexError: list index out of range

**Comment by AliciaSchep** [comment]
Something seems like its going wrong with reading in the bed file.  What do the first few lines of the bed file look like?  (The error is happening because when the script is trying to merge any overlapping bed regions there seems to be no bed regions that have actually been read in)

**Comment by sprescot** [comment]
Hey Alicia! I know this was posted a while ago, but I'm following up because I'm running into a similar problem when trying it on our human neural crest ATAC data. The NucleoATAC software runs and outputs an output_basename.occ.bedgraph.gz file which is truncated part of the way through chromosome 1. Here are my error messages:

Command run:  /data1/sprescot/python_virtual/bin/nucleoatac run --bed EnhancerClass_Strong_BED3.txt --bam human_ncc_atac_sort.bam --out HumanNCC_StrongEnhancersOnly --fasta ../../genomics/genomes/hg19.fa --cores 20
nucleoatac version 0.3.1
start run at: 2015-11-13 16:08
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
/data1/sprescot/python_virtual/local/lib/python2.7/site-packages/pyatac/chunk.py:174: UserWarning: 1 chromosome names in bed file not included in FASTA file:
chr17_gl000204_random
 These regions will be ignored in subsequent analysis
  warnings.warn(warn_message)
Making figure
---------Step2: Processing Vplot------------------------------------------------
---------Step3: Obtaining nucleosome signal and calling positions---------------
Traceback (most recent call last):
  File "/data1/sprescot/python_virtual/bin/nucleoatac", line 291, in <module>
    main()
  File "/data1/sprescot/python_virtual/bin/nucleoatac", line 79, in main
    run_nuc(nuc_args)
  File "/data1/sprescot/python_virtual/local/lib/python2.7/site-packages/nucleoatac/run_nuc.py", line 153, in run_nuc
    chunks.merge()
  File "/data1/sprescot/python_virtual/local/lib/python2.7/site-packages/pyatac/chunk.py", line 114, in merge
    previous = self[0]
IndexError: list index out of range

Thanks a lot for your help!
Sara

**Comment by AliciaSchep** [comment]
I have not figured out what causes this problem (haven't been able to reproduce it).   @sprescot could you include what the last lines of the truncated output_basename.occ.bedgraph.gz are?  And the format of the bed file?  (i.e what first few lines of bed file look like).

**Comment by sprescot** [comment]
Hey Alicia, seems it was a false alarm. I reran it using the same command and the output_basename.occ.bedgraph.gz was not truncated this time. It still displays the same error messages (IndexError: list index out of range) but all the files look correct, so I think I can ignore it. Thanks anyways for your help.

**Comment by PFRoux** [comment]
Hi there,

I went through the same issue as reported by Lopatica. And I figured out it was related to the .bed generated by MACS2. Actually, before running NucleoATAC, you have to remove the .bed header that describes the .bed file. 

Hope that could help others. 

Pierre-François

**Comment by AliciaSchep** [comment]
Thanks for figuring out this issue!  I should enable the function that reads the bed file to skip the first line if it looks like a header.
