### ISSUE TITLE
ValueError: invalid reference 

### ISSUE THREAD

**Issue by OscarBrock** [GreenleafLab/NucleoATAC#30]
Hi Alicia, 
I'm trying things out on some new data and am getting a value error; any sense of what the problem might be?

Command run:  /gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac run --bed /gne/home/bainerr/Workspace/ATACseq/Classon/PC9_reps/allReps.bed --bam /gne/home/bainerr/Workspace/ATACseq/Classon/PC9_reps/R1_15m.bam --fasta /gne/research/apps/ngs_pipeline/4.0.2/x86_64-linux-2.6-rhel6/genome_files/GATK/GRCm38.fa --out R1_15m
nucleoatac version 0.3.1
start run at: 2015-12-04 09:53
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Traceback (most recent call last):
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 291, in <module>
    main()
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/bin/nucleoatac", line 75, in main
    run_occ(occ_args)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 95, in run_occ
    fragment_dist.getFragmentSizes(args.bam, chunks)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 28, in getFragmentSizes
    self.fragmentsizes.calculateSizes(bamfile, chunks = chunklist)
  File "/gne/home/bainerr/miniconda3/envs/ATACseq/lib/python2.7/site-packages/pyatac/fragmentsizes.py", line 26, in calculateSizes
    sizes = getFragmentSizesFromChunkList(chunks, bamfile, self.lower, self.upper, atac = self.atac)
  File "pyatac/fragments.pyx", line 130, in pyatac.fragments.getFragmentSizesFromChunkList (/gne/home/bainerr/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:4723)
  File "pysam/calignmentfile.pyx", line 727, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:9892)
  File "pysam/calignmentfile.pyx", line 641, in pysam.calignmentfile.AlignmentFile._parseRegion (pysam/calignmentfile.c:8888)
ValueError: invalid reference `1`

Also, I'm noticing that when I run the current version of the code it seems to hang on the 5th step (or at least runs for more than a week). This hasn't been critical for my purposes as I get the remaining outputs, but if you have an idea of how I can troubleshoot effectively I'd appreciate it.

**Comment by AliciaSchep** [comment]
What is the chromosome naming convention for both the bed file and the bam file?  (for bam file, what is the output of `samtools view -H bamfile.bam`?

The 5th step should not be relatively quick compared to steps 1 and 3 so that does seem to be like something is going wrong...  Is any output produced at all?  If so, does the output stop growing and at what region does it do so?

**Comment by AliciaSchep** [comment]
Ok I saw your post about the NFR problem in the other issue... I think I know what to look for.  I will get back to you if/when I figure out exactly what the issue is.

**Comment by OscarBrock** [comment]
Ah, I see the issue- I'm using some files that were aligned by a different
group, apparently using different naming conventions. Thank you.

-R
