### ISSUE TITLE
error in nucleoatac run

### ISSUE THREAD

**Issue by yanbianqu** [GreenleafLab/NucleoATAC#33]
Hi Alicia, 
I am exciting to try NucleoAtac, 
I run   nucleoatac run and get the following error 

nucleoatac version 0.3.1
start run at: 2016-01-21 13:38
/usr/local/lib/python2.7/dist-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/usr/local/bin/nucleoatac", line 291, in <module>
    main()
  File "/usr/local/bin/nucleoatac", line 69, in main
    from nucleoatac.run_occ import run_occ
  File "/usr/local/lib/python2.7/dist-packages/nucleoatac/run_occ.py", line 19, in <module>
    from nucleoatac.Occupancy import FragmentMixDistribution, OccupancyParameters, OccChunk
  File "/usr/local/lib/python2.7/dist-packages/nucleoatac/Occupancy.py", line 12, in <module>
    from pyatac.fragmentsizes import FragmentSizes
  File "/usr/local/lib/python2.7/dist-packages/pyatac/fragmentsizes.py", line 10, in <module>
    from pyatac.fragments import getAllFragmentSizes, getFragmentSizesFromChunkList
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.22-py2.7-linux-x86_64.egg/pyximport/pyximport.py", line 431, in load_module
    language_level=self.language_level)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.22-py2.7-linux-x86_64.egg/pyximport/pyximport.py", line 210, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "pysam/cfaidx.pxd", line 21, in init pyatac.fragments (/home/qu/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:7547)
ImportError: Building module pyatac.fragments failed: ['ValueError: pysam.cfaidx.FastqProxy has the wrong size, try recompiling\n']

python 2.7.6
numpy  1.10.4
scipy 0.16.1
cython 0.22
pysam 0.8.4

on Ubuntun 14.04

Thanks!

**Comment by AliciaSchep** [comment]
Not sure what is going on here, some issue with loading a file from pysam.  I would suggest trying to reinstall pysam, especially as error message says "try recompiling" in reference to the error with the file from pysam.

**Comment by yanbianqu** [comment]
Thanks,
 I change to pysam 0.8.2, it works properly now.
by recompiling 0.8.3 or install pysam 0.8.1, the error keeps.
I don't know the reason.
