### ISSUE TITLE
RuntimeWarnings and ValueErrors

### ISSUE THREAD

**Issue by msuperd1** [GreenleafLab/NucleoATAC#37]
Hi,

I am a new user of NucleoATAC, and I have been able to run the test examples without any problem. However, when I try using NucleoATAC on my own ATAC data, I run into 1 of 2 issues.

Here is the first issue. In this case, I get a RuntimeWarning from numpy. It is generated as a result of a divide by zero error in Step 3. In this case the output still seems to be created despite the warning. I've included the standard output below:

Command run:  /usr/bin/nucleoatac run --bam 150407/AC8.sorted.bam --bed test.bed --fasta hg19_genome.fa --out AC8_test
nucleoatac version 0.3.2
start run at: 2016-04-27 16:56
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Making figure
---------Step2: Processing Vplot------------------------------------------------
---------Step3: Obtaining nucleosome signal and calling positions---------------
/usr/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:120: RuntimeWarning: divide by zero encountered in log
  nuc_lik = np.sum(np.log(nuc_model) \* mat)
/usr/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:120: RuntimeWarning: invalid value encountered in multiply
  nuc_lik = np.sum(np.log(nuc_model) \* mat)
/usr/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:121: RuntimeWarning: divide by zero encountered in log
  null_lik = np.sum(np.log(null_model) \* mat)
/usr/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:121: RuntimeWarning: invalid value encountered in multiply
  null_lik = np.sum(np.log(null_model) \* mat)
---------Step4: Making combined nucleosome position map ------------------------
---------Step5: Calling NFR positions-------------------------------------------
end run at: 2016-04-27 16:56

Here is the second issue. In this case I get another numpy RuntimeWarning. It is created as a result of an overflow in Step 1. Subsequently, there is a ValueError. This causes the program to crash.

Command run:  /usr/bin/nucleoatac run --bam 150407/AC6.sorted.bam --bed test.bed --fasta hg19_genome.fa --out AC6_test
nucleoatac version 0.3.2
start run at: 2016-04-27 17:19
---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
/usr/lib/python2.7/site-packages/nucleoatac/Occupancy.py:45: RuntimeWarning: overflow encountered in power
  res[nz] = a \* x_mod[nz]*_(k-1) \* np.exp(-x_mod[nz]/theta) / (theta *_k \* gamma(k))
Traceback (most recent call last):
  File "/usr/bin/nucleoatac", line 31, in <module>
    nucleoatac_main(args)
  File "/usr/lib/python2.7/site-packages/nucleoatac/cli.py", line 56, in nucleoatac_main
    run_occ(occ_args)
  File "/usr/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 96, in run_occ
    fragment_dist.modelNFR()
  File "/usr/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 65, in modelNFR
    nuc[nuc<=0]=min(min(nfr)_0.1,min(nuc[nuc>0])_0.001)
ValueError: min() arg is an empty sequence

nuceloATAC (0.3.2)
python (2.7.5)
numpy (1.11.0)

Any insight would be greatly appreciated!

**Comment by msuperd1** [comment]
Both issues occurred when using a BED file that was too small (smaller than the example file). The issue did not re-occur when using a larger BED file.
