### ISSUE TITLE
Problem building pyatac.fragments

### ISSUE THREAD

**Issue by cdeboever3** [GreenleafLab/NucleoATAC#4]
Hi @AliciaSchep ,

I'm trying to run `nucleoatac run` and having an issue:

```
nucleoatac run --bed test_sorted.bed --bam ctc1_d15_combined.bam --out test_sorted --fasta ../../external_data/hg19/hg19.fa
Command run:  /raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/bin/nucleoatac run --bed test_sorted.bed --bam ctc1_d15_combined.bam --out test_sorted --fasta ../../external_data/hg19/hg19.fa
nucleoatac version 0.1.4
start run at: 2015-05-14 14:03
/home/cdeboever/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:250:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"                               ^
compilation terminated.
Traceback (most recent call last):
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/bin/nucleoatac", line 217, in <module>
    main()  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/bin/nucleoatac", line 54, in main
    from nucleoatac.run_occ import run_occ
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 19, in <module>
    from nucleoatac.Occupancy import FragmentMixDistribution, OccupancyParameters, OccChunk
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 12, in <module>
    from pyatac.fragmentsizes import FragmentSizes
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/pyatac/fragmentsizes.py", line 10, in <module>
    from pyatac.fragments import getAllFragmentSizes, getFragmentSizesFromChunkList  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/pyximport/pyximport.py", line 431, in load_module    language_level=self.language_level)
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/pyximport/pyximport.py", line 209, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/pyximport/pyximport.py", line 186, in build_module
    reload_support=pyxargs.reload_support)
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 100, in pyx_to_dll
    dist.run_commands()
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/distutils/dist.py", line 972, in run_command    cmd_obj.run()
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run    _build_ext.build_ext.run(self)
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 171, in build_extensions
    self.build_extension(ext)  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/distutils/command/build_ext.py", line 496, in build_extension
    depends=ext.depends)  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/raid/development/cdeboever/software/anaconda1.9.1/envs/cardips-tc/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile    raise CompileError, msg
ImportError: Building module pyatac.fragments failed: ["CompileError: command 'gcc' failed with exit status 1\n"]
```

I have cython 0.22 and numpy 1.9.1 installed with python 2.7.9. I'm also running on openSUSE 13.2. I'm trying to debug it a bit but I haven't used cython much so I haven't had too much luck.

**Comment by AliciaSchep** [comment]
I have made a change\* that I think may fix this issue in a branch called "issue4".  @cdeboever3, would you be able to try checking that branch out to see if the change fixes the problem on your system? 

*changing `pyximport.install()` to `pyximport.install(setup_args={"include_dirs": np.get_include()})` within all applicable scripts

**Comment by cdeboever3** [comment]
Thanks @AliciaSchep that solved it. I was able to use `nucleoatac run` for a small set of intervals successfully. Cool stuff.

**Comment by AliciaSchep** [comment]
Great, thanks for trying the new branch.  I have merged "issue4"  into the master branch.
