### ISSUE TITLE
ValueError with NucleoATAC

### ISSUE THREAD

**Issue by Scubatuba99** [GreenleafLab/NucleoATAC#48]
I try running NucleoATAC with a bed file flanking TSS's, and I get the following error:

Traceback (most recent call last):
  File "/Users/Eric/anaconda/envs/nucleoatac/bin/nucleoatac", line 31, in <module>
    nucleoatac_main(args)
  File "/Users/Eric/anaconda/envs/NucleoATAC/lib/python2.7/site-packages/nucleoatac/cli.py", line 56, in nucleoatac_main
    run_occ(occ_args)
  File "/Users/Eric/anaconda/envs/NucleoATAC/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 86, in run_occ
    chunks = ChunkList.read(args.bed, chromDict = chrs, min_offset = args.flank + args.upper/2 + max(pwm.up,pwm.down) + args.nuc_sep/2)
  File "/Users/Eric/anaconda/envs/NucleoATAC/lib/python2.7/site-packages/pyatac/chunk.py", line 155, in read
    end = int(in_line[2])
ValueError: invalid literal for int() with base 10: '3206415\rchr1'

I looked at the bedfile and that value is on the first line of the bedfile.  What's going on, what did I do?

**Comment by AliciaSchep** [comment]
Looks like the issue is with reading in the bed file for the peaks, in particular that the line endings are not as expected... '\r' instead of '\n'.  For reading in the file properly it expect '\n' line endings.

**Comment by Scubatuba99** [comment]
Simple fix, thanks!  Program is running.
