### ISSUE TITLE
Error compiling Cython file

### ISSUE THREAD

**Issue by IanCodes** [GreenleafLab/NucleoATAC#53]
I am having a problem using NucleoATAC 0.3.2. NucleoATAC install OK in a virtualenv using the following script:
virtualenv venv.NucleoATAC-0.3.2
. venv.NucleoATAC-0.3.2/bin/activate
pip install numpy
pip install scipy
pip install matplotlib
pip install cython
pip install pysam
git clone https://github.com/GreenleafLab/NucleoATAC.git
cd NucleoATAC/
pip install .

The output is shown below:
Processing ~/virtualenvs/NucleoATAC
Requirement already satisfied: cython>=0.22 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from NucleoATAC==0.3.2)
Requirement already satisfied: numpy>=1.9.1 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from NucleoATAC==0.3.2)
Requirement already satisfied: scipy>=0.16.0 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from NucleoATAC==0.3.2)
Requirement already satisfied: pysam>=0.8.1 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from NucleoATAC==0.3.2)
Requirement already satisfied: matplotlib in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from NucleoATAC==0.3.2)
Requirement already satisfied: cycler>=0.10 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Requirement already satisfied: python-dateutil in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Requirement already satisfied: functools32 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Requirement already satisfied: six>=1.10 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Requirement already satisfied: pytz in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Requirement already satisfied: subprocess32 in ~/virtualenvs/venv.NucleoATAC-0.3.2/lib/python2.7/site-packages (from matplotlib->NucleoATAC==0.3.2)
Installing collected packages: NucleoATAC
Running setup.py install for NucleoATAC ... done
Successfully installed NucleoATAC-0.3.2

However, I get an error message concerning cython when I run the first stage, using the following script:
nucleoatac run --bed atac_summits_pm250_sorted.bed --bam atac.bam --fasta genome.fa --out atac_summits_pm250_NucleoATAC

The error output is in the attached file.
https://github.com/GreenleafLab/NucleoATAC/files/745216/nucleoatac_error.txt

I am using Linux Ubuntu x64 v16.04.

Thanks in advance for any help you can give.

EDIT:

I have also tried version 0.3.1, and got a similar set of errors:
Command run:  ~/virtualenvs/venv.NucleoATAC-0.3.1/bin/nucleoatac run --bed atac.bed --bam atac.bam --fasta genome.fa --out atac_NucleoATAC --cores 8
nucleoatac version 0.3.1
start run at: 2017-02-02 09:37
~/.pyxbld/temp.linux-x86_64-2.7/pyrex/pyatac/fragments.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
Traceback (most recent call last):
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/bin/nucleoatac", line 291, in <module>
    main()
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/bin/nucleoatac", line 69, in main
    from nucleoatac.run_occ import run_occ
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 19, in <module>
    from nucleoatac.Occupancy import FragmentMixDistribution, OccupancyParameters, OccChunk
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 12, in <module>
    from pyatac.fragmentsizes import FragmentSizes
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/pyatac/fragmentsizes.py", line 10, in <module>
    from pyatac.fragments import getAllFragmentSizes, getFragmentSizesFromChunkList
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "~/virtualenvs/venv.NucleoATAC-0.3.1/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
ImportError: Building module pyatac.fragments failed: ["CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]

**Comment by AliciaSchep** [comment]
Not sure exactly source of error, seems to be issue with Cython -- what version of Cython are you using?

**Comment by Zhenhuiz** [comment]
Hi Alicia,

I also got the same problem. The installation looks successed. But when I run it on Virtual Environment, I got the same error message.  
Error compiling Cython file:
------------------------------------------------------------
...
@cython.boundscheck(False)
def getFragmentSizesFromChunkList(chunks, str bamfile, int lower, int upper, int                 atac = 1):
    cdef np.ndarray[DTYPE_t, ndim =1] sizes = np.zeros(upper - lower, dtype= np.                float)
    # loop over samfile
    cdef AlignmentFile bamHandle = AlignmentFile(bamfile)
    cdef AlignedSegment read
        ^

My cython is 0.25.2.

Thank  you!

**Comment by AliciaSchep** [comment]
I think this is due to updates with Pysam.  One possible temporary solution is to install older version of pysam, but I will update the code shortly to be compatible with the newest version of pysam.

**Comment by AliciaSchep** [comment]
I have updated the code to be compatible with new pysam version; the NucleoATAC update to v0.3.3 should work with Pysam v0.10.0

**Comment by IanCodes** [comment]
Now appears to be working correctly.  Thank you.
