### ISSUE TITLE
fatal error: 'numpy/arrayobject.h' file not found

### ISSUE THREAD

**Issue by kesteph** [GreenleafLab/NucleoATAC#64]
Hello
I installed the most recent version of nucleoatac and am now receiving the following error.  It seems that the program is looking for "numpy/arrayobject.h".  I'm not too familiar with Python.  Can you advise?

I am using Python 2.7.10 with the following dependencies installed:
Cython==0.26
pysam==0.11.2.2
numpy==1.13.1
scipy==0.19.1
matplotlib==2.0.2

thank you
Kim

Lucy:nucleoATAC kims$ nucleoatac run --bed macs2.Cpeaks.bed --bam ATACMC.bam --fasta /Users/kims/ReferenceGenomes/rn6.fa --out ATACMC.NucleoATAC --cores 8
Command run:  /usr/local/bin/nucleoatac run --bed macs2.Cpeaks.bed --bam ATACMC.bam --fasta /Users/kims/ReferenceGenomes/rn6.fa --out ATACMC.NucleoATAC --cores 8
nucleoatac version 0.3.4
start run at: 2017-07-30 15:40
/Users/kims/.pyxbld/temp.macosx-10.12-x86_64-2.7/pyrex/pyatac/fragments.c:435:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 error generated.
Traceback (most recent call last):
  File "/usr/local/bin/nucleoatac", line 33, in <module>
    nucleoatac_main(args)
  File "/usr/local/lib/python2.7/site-packages/nucleoatac/cli.py", line 50, in nucleoatac_main
    from nucleoatac.run_occ import run_occ
  File "/usr/local/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 19, in <module>
    from nucleoatac.Occupancy import FragmentMixDistribution, OccupancyParameters, OccChunk
  File "/usr/local/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 12, in <module>
    from pyatac.fragmentsizes import FragmentSizes
  File "/usr/local/lib/python2.7/site-packages/pyatac/fragmentsizes.py", line 10, in <module>
    from pyatac.fragments import getAllFragmentSizes, getFragmentSizesFromChunkList
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
ImportError: Building module pyatac.fragments failed: ["CompileError: command 'clang' failed with exit status 1\n"]

**Comment by AliciaSchep** [comment]
this is on a mac? also, to clarify, had you previously run earlier version of nucleoatac without issue but now see this error with most recent error, or is this the first version you have tried?

**Comment by kesteph** [comment]
Hi Alicia
Yes, I am trying to run this on macOS 10.12.6.
I have used previous versions without difficulty, but this is the first installation of NucleoATAC on this machine.
thank you

On Jul 30, 2017, at 23:58, Alicia Schep <notifications@github.com<mailto:notifications@github.com>> wrote:


this is on a mac? also, to clarify, had you previously run earlier version of nucleoatac without issue but now see this error with most recent error, or is this the first version you have tried?

**Comment by sarawernig** [comment]
Has this issue been resolved? I have exactly the same problem installing on macOS 10.14.3.

**Comment by kesteph** [comment]
No I never received a response, but I was able to install it on another system running Linux.

On Feb 28, 2019, at 11:19, Fluorine <notifications@github.com<mailto:notifications@github.com>> wrote:


Has this issue been resolved? I have exactly the same problem installing on macOS 10.14.3.

**Comment by sarawernig** [comment]
I solved it by installing it via conda. For some reason, this works on MacOS. 

`conda install -c bioconda nucleoatac`
