### ISSUE TITLE
`nucpos` files are empty

### ISSUE THREAD

**Issue by sameet** [GreenleafLab/NucleoATAC#70]
Hi,
I did the following:
1. Ran `bwa mem` for the alignment.
2. Used `macs2` to call peaks (`broad` peaks).
3. Used the `NucleoATAC` pipeline as given in the help documents.  

The pipeline ran without errors.  However, the `nucpos` output was empty.  It still generated other files that are non-empty, including `nfr` files that also seem to have data.  Am I missing something?

**Comment by AliciaSchep** [comment]
Please see Issue #55 and discussion there -- might be same problem.

**Comment by sameet** [comment]
Hi @AliciaSchep,
I looked at Issue #55, and tried the following.
Briefly, I deleted the `.pyxbld` from my home directory.  Then i used `python tests.py`.  It forced re-compile of the `C` part of the code. I used the GCC 5.4.0. I still get the following error:

    ======================================================================
    FAIL: Make sure variance calculation is close to what is obtained by simulation
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/gpfs/ycga/home/sm2556/GitHub/NucleoATAC/tests/test_var.py", line 33, in test_sd1 
        self.assertTrue(abs(sd1-sd2)<0.05*sd1)
    AssertionError: False is not true

    ======================================================================
    FAIL: Make sure variance calculation is same as would be obtained through alternate calculation
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/gpfs/ycga/home/sm2556/GitHub/NucleoATAC/tests/test_var.py", line 43, in test_sd2
        self.assertTrue(abs(sd1-sd2)<0.001*sd1)
    AssertionError: False is not true

    ----------------------------------------------------------------------
    Ran 24 tests in 205.134s

My `python` is 2.7.13.  What should be my next step?

    [sm2556@c13n06 NucleoATAC]$ strings -a ~/.pyxbld/lib.linux-x86_64 2.7/nucleoatac/multinomial_cov.so | grep "GCC: ("
    GCC: (GNU) 5.4.0

The problem persists.
