### ISSUE TITLE
NucleoATAC installation 

### ISSUE THREAD

**Issue by srogue50** [GreenleafLab/NucleoATAC#8]
Hi Alicia, I am excited to try out NucleoATAC. I have installed in a virtual environment with all dependencies, but I keep running into a ton of unused function errors followed by the final error, the most informative of which I think is:

ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/Library/Python/2.7/site-packages/pysam/TabProxies.so' for architecture x86_64

I am running from a mac OS X terminal and I think from looking up the above error that this is my problem. Has anyone else installed NucleoATAC in an OS X terminal? Any help would be greatly appreciated--Thanks again

Dave

37 warnings generated.
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '/Library/Python/2.7/site-packages/pysam/TabProxies.so' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/usr/local/bin/pyatac", line 359, in <module>
    main()
  File "/usr/local/bin/pyatac", line 49, in main
    from pyatac.get_ins import get_ins
  File "/Library/Python/2.7/site-packages/pyatac/get_ins.py", line 16, in <module>
    from pyatac.tracks import InsertionTrack
  File "/Library/Python/2.7/site-packages/pyatac/tracks.py", line 13, in <module>
    from fragments import getInsertions, getStrandedInsertions
  File "/Library/Python/2.7/site-packages/pyximport/pyximport.py", line 431, in load_module
    language_level=self.language_level)
  File "/Library/Python/2.7/site-packages/pyximport/pyximport.py", line 209, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/Library/Python/2.7/site-packages/pyximport/pyximport.py", line 186, in build_module
    reload_support=pyxargs.reload_support)
  File "/Library/Python/2.7/site-packages/pyximport/pyxbuild.py", line 100, in pyx_to_dll
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Library/Python/2.7/site-packages/Cython/Distutils/build_ext.py", line 163, in run
    _build_ext.build_ext.run(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/Library/Python/2.7/site-packages/Cython/Distutils/build_ext.py", line 171, in build_extensions
    self.build_extension(ext)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 528, in build_extension
    target_lang=language)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 691, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 200, in link
    raise LinkError, msg
ImportError: Building module pyatac.fragments failed: ["LinkError: command 'cc' failed with exit status 1\n"]

**Comment by srogue50** [comment]
I forgot to mention, I was running the following pyatac with the example.bam.

 pyatac ins --bam  ./example/example.bam

**Comment by AliciaSchep** [comment]
Hi Dave, to me that looks like it might be an issue arising from NucleoATAC and/or pysam's use of Cython

1) could you check which version of cython gets imported in your virtualenv (i.e if in python you do `import cython; cython.__version__` what version does it say?)  I've had issues before where even after supposedly updating cython the old version would still get imported by default so want to be sure that isn't the issue here, as I know that using old versions causes problems 

2) Check out http://stackoverflow.com/questions/22697440/cc-failed-with-exit-status-1-error-when-install-python-library for similar errors with another python installation and possible solutions that may be applicable to your installation attempt

**Comment by srogue50** [comment]
Thanks for the reply--I am running Cython 0.22. Thanks for the link, I tried the solutions outlined to no avail. I will keep looking and trying. Thanks again

**Comment by srogue50** [comment]
Hi Alicia, 
I got nucleoatac running through setting up a virtual Ubuntu machine, I don't know if my OS X terminal installation was an issue with my specific set up or with OS X installation in general, so I thought I would leave my solution here in case anyone else has the same problem. Thanks again!

**Comment by DoaneAS** [comment]
I was also having this problem, which was related to the clang compiler on OSX in my case.  The solution that worked for me was to install with ` sudo -E python setup.py install` rather than `pip install .`
