### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by michaelwillcockson** [GreenleafLab/NucleoATAC#82]
I'm generating "IndexError:list index out of range". When I use nucleoatac run. The samtools index mm9.fa.fai is in the same directory as mm9.fa. Full error below.

nucleoatac run --bed dir1/file.bed --bam file.bam --fasta dir2/mm9.fa --out file.nucAtac

---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
Traceback (most recent call last):
  File "/Users/michaelwillcockson/arch/Darwin-x86_64/bin/nucleoatac", line 33, in <module>
    nucleoatac_main(args)
  File "/Users/michaelwillcockson/Computational/bin/NucleoATAC/nucleoatac/cli.py", line 56, in nucleoatac_main
    run_occ(occ_args)
  File "/Users/michaelwillcockson/Computational/bin/NucleoATAC/nucleoatac/run_occ.py", line 86, in run_occ
    chunks = ChunkList.read(args.bed, chromDict = chrs, min_offset = args.flank + args.upper/2 + max(pwm.up,pwm.down) + args.nuc_sep/2)
  File "/Users/michaelwillcockson/Computational/bin/NucleoATAC/pyatac/chunk.py", line 154, in read
    start = int(in_line[1])
IndexError: list index out of range

**Comment by michaelwillcockson** [comment]
Found a similar question earlier, sorry for the repeat. This is caused be a poorly formed bed file. In this case I had the wrong field separator.
