### ISSUE TITLE
error with module nfr

### ISSUE THREAD

**Issue by LuccaZhao** [GreenleafLab/NucleoATAC#85]

**Comment by LuccaZhao** [comment]
I got all files with module occ, nuc, vprocess, merge, but when I tried to run nfr, there was one error:

Command run:  /software/python/python-2.7.6/bin/nucleoatac nfr --bed /data1/zhao_xm/Align/DXFA/BED_0321B_DXFA_peaks.broadPeak.bed --occ_track DXFA.occ.bedgraph.gz.tbi --calls DXFA.nucpos.bed.gz --bam /data1/zhao_xm/Align/DXFA/DXFA.bam --out DXFA --cores 20
nucleoatac version 0.3.4
start run at: 2019-03-21 18:25
---------Calling NFR positions--------------------------------------------------
Traceback (most recent call last):
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/run_nfr.py", line 27, in _nfrHelper
    nfr.process(params)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 103, in process
Traceback (most recent call last):
    self.getOcc()
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/run_nfr.py", line 27, in _nfrHelper
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 63, in getOcc
    self.occ.read_track(self.params.occ_track)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/tracks.py", line 84, in read_track
Traceback (most recent call last):
    handle = BedGraphFile(bedgraph)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/bedgraph.py", line 8, in __init__
    nfr.process(params)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 103, in process
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/run_nfr.py", line 27, in _nfrHelper
    self.tbx = pysam.Tabixfile(bedgraph)
  File "pysam/libctabix.pyx", line 351, in pysam.libctabix.TabixFile.__cinit__
    self.getOcc()
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 63, in getOcc
    self.occ.read_track(self.params.occ_track)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/tracks.py", line 84, in read_track
Traceback (most recent call last):
    nfr.process(params)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 103, in process
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/run_nfr.py", line 27, in _nfrHelper
    handle = BedGraphFile(bedgraph)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/bedgraph.py", line 8, in __init__
    self.tbx = pysam.Tabixfile(bedgraph)
  File "pysam/libctabix.pyx", line 351, in pysam.libctabix.TabixFile.__cinit__
    self.getOcc()
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 63, in getOcc
  File "pysam/libctabix.pyx", line 383, in pysam.libctabix.TabixFile._open
    self.occ.read_track(self.params.occ_track)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/tracks.py", line 84, in read_track
    nfr.process(params)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 103, in process
    self.getOcc()
    handle = BedGraphFile(bedgraph)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/nucleoatac/NFRCalling.py", line 63, in getOcc
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/bedgraph.py", line 8, in __init__
    self.occ.read_track(self.params.occ_track)
  File "/data1/software/python/python-2.7.6/lib/python2.7/site-packages/NucleoATAC-0.3.4-py2.7.egg/pyatac/tracks.py", line 84, in read_track
    self.tbx = pysam.Tabixfile(bedgraph)
  File "pysam/libctabix.pyx", line 351, in pysam.libctabix.TabixFile.__cinit__
IOError: index `DXFA.occ.bedgraph.gz.tbi.tbi` not found

Could you give me some clues to solve this problem? Thank you!

**Comment by NachoFraga95** [comment]
I have the same issue, i gave the bed file, occ, nucpos and my .bam file is sorted and indexed, i gave fasta file as well, and got the error:
IOError: index `OS24_nucleosomas.occ.bedgraph.gz.occ.bedgraph.tbi` not found
