### ISSUE TITLE
nucleoatac crashing after running partially

### ISSUE THREAD

**Issue by laulabbrandeis** [GreenleafLab/NucleoATAC#9]
I thought I got nucleoatac to work properly until I realized that it crashed after producing partial output. I am getting the following error message. I happy to provide other supporting files if needed. Any help is highly appreciated.

> > > > > > > > > Command run:  /usr/local/bin/anaconda/bin/nucleoatac run --bed Brain_ZT2_PE_peaks.broadPeak --bam Brain_ZT2_PE_nodup.sort.bam --fasta /data/theia/analysis/dm3/Sequence/bowtie_indexes/genome.fa --out Brain_ZT2_PE_nucleoATAC
> > > > > > > > > nucleoatac version 0.2.1
> > > > > > > > > start run at: 2015-08-01 22:40
> > > > > > > > > ---------Step1: Computing Occupancy and Nucleosomal Insert Distribution---------
> > > > > > > > > Traceback (most recent call last):
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 30, in _occHelper
> > > > > > > > >     occ.process(params)
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 229, in process
> > > > > > > > >     self.callPeaks()
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/site-packages/nucleoatac/Occupancy.py", line 208, in callPeaks
> > > > > > > > >     peaks = call_peaks(self.occ.smoothed_vals, sep = self.params.sep, min_signal = self.params.min_occ)
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/site-packages/pyatac/utils.py", line 98, in call_peaks
> > > > > > > > >     peaks = peaks[sigvals[peaks] >= min_signal ]
> > > > > > > > > IndexError: arrays used as indices must be of integer (or boolean) type
> > > > > > > > > Traceback (most recent call last):
> > > > > > > > >   File "/usr/local/bin/anaconda/bin/nucleoatac", line 291, in <module>
> > > > > > > > >     main()
> > > > > > > > >   File "/usr/local/bin/anaconda/bin/nucleoatac", line 75, in main
> > > > > > > > >     run_occ(occ_args)
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/site-packages/nucleoatac/run_occ.py", line 116, in run_occ
> > > > > > > > >     tmp = pool1.map(_occHelper, zip(j,itertools.repeat(params)))
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/multiprocessing/pool.py", line 250, in map
> > > > > > > > >     return self.map_async(func, iterable, chunksize).get()
> > > > > > > > >   File "/usr/local/bin/anaconda/lib/python2.7/multiprocessing/pool.py", line 554, in get
> > > > > > > > >     raise self._value
> > > > > > > > > IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by davek44** [comment]
Hi, I'm experiencing the same problem. I'm providing a sorted BAM and broadPeak output from MACS2, but get the following error. I'm happy to provide any other information that might help resolve it.

[dkelley@dkelley01 rep1]$ nucleoatac occ --bed broad/NA_peaks.broadPeak --bam combine.bam --out occ --fasta $HG19/sequence/hg19.fa
Command run:  /n/home03/dkelley/.local/bin/nucleoatac occ --bed broad/NA_peaks.broadPeak --bam combine.bam --out occ --fasta /n/home03/dkelley/research/common/data/genomes/hg19/sequence/hg19.fa
nucleoatac version 0.2.1
start run at: 2015-08-19 19:32
---------Computing Occupancy and Nucleosomal Insert Distribution----------------
Caught exception when processing:
chr1    38552   38864   None    None    +

Traceback (most recent call last):
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_occ.py", line 30, in _occHelper
    occ.process(params)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/Occupancy.py", line 229, in process
    self.callPeaks()
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/Occupancy.py", line 208, in callPeaks
    peaks = call_peaks(self.occ.smoothed_vals, sep = self.params.sep, min_signal = self.params.min_occ)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/pyatac/utils.py", line 98, in call_peaks
    peaks = peaks[sigvals[peaks] >= min_signal ]
IndexError: arrays used as indices must be of integer (or boolean) type
()
Traceback (most recent call last):
  File "/n/home03/dkelley/.local/bin/nucleoatac", line 5, in <module>
    pkg_resources.run_script('NucleoATAC==0.2.1', 'nucleoatac')
  File "/n/home03/dkelley/lib/python2.7/site-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/n/home03/dkelley/lib/python2.7/site-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 291, in <module>
    main()
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/EGG-INFO/scripts/nucleoatac", line 36, in main
    run_occ(args)
  File "/n/home03/dkelley/.local/lib/python2.7/site-packages/NucleoATAC-0.2.1-py2.7.egg/nucleoatac/run_occ.py", line 116, in run_occ
    tmp = pool1.map(_occHelper, zip(j,itertools.repeat(params)))
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by AliciaSchep** [comment]
This turned out to be an issue with the numpy version.  I have added a requirement to the most recent code for a recent version of numpy.  The scipy version is also important, version 0.13.0 will not work.  Haven't figured out what minimal version of scipy needed is yet

**Comment by davek44** [comment]
Updating those libraries got past these errors for me. Thanks!
