### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by juechenyang** [GreenleafLab/NucleoATAC#93]
Hi,

I was trying to run nucleoATAC on my linux machine. However I always got the following errors when I was using command "nucleoatac run --bed my.bed --bam my.bam --fasta GRCh38_latest_genomic.fasta --out ./ ":

**py:174: UserWarning: 24 chromosome names in bed file not included in FASTA file:
chrY
chrX
chr13
chr12
chr11
chr10
chr17
chr16
chr15
chr14
chr19
chr18
chr22
chr20
chr21
chr7
chr6
chr5
chr4
chr3
chr2
chr1
chr9
chr8
 These regions will be ignored in subsequent analysis
  warnings.warn(warn_message)
Traceback (most recent call last):
  File "/home/CBBI/yangj8/miniconda3/envs/py27/bin/nucleoatac", line 33, in <mod                                      ule>
    nucleoatac_main(args)
  File "/home/CBBI/yangj8/miniconda3/envs/py27/lib/python2.7/site-packages/nucle                                      oatac/cli.py", line 56, in nucleoatac_main
    run_occ(occ_args)
  File "/home/CBBI/yangj8/miniconda3/envs/py27/lib/python2.7/site-packages/nucle                                      oatac/run_occ.py", line 88, in run_occ
    chunks.merge()
  File "/home/CBBI/yangj8/miniconda3/envs/py27/lib/python2.7/site-packages/pyata                                      c/chunk.py", line 114, in merge
    previous = self[0]
IndexError: list index out of range**

Here is also my pip list for your reference:

Package                       Version

backports.functools-lru-cache 1.6.1
certifi                       2019.11.28
cycler                        0.10.0
Cython                        0.29.21
kiwisolver                    1.1.0
matplotlib                    2.2.5
NucleoATAC                    0.3.4
numpy                         1.16.6
pip                           20.1.1
pyparsing                     2.4.7
pysam                         0.16.0.1
python-dateutil               2.8.1
pytz                          2020.1
scipy                         1.2.3
setuptools                    44.0.0.post20200102
six                           1.15.0
subprocess32                  3.5.4
wheel                         0.35.1

Would you mind help me to check what reasons causing this error and how to fix them? Thanks!

**Comment by juechenyang** [comment]
I think I have figured out it. It's just because my fasta was styled as "chromosome X" rather than "chr X".
